eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:7776/eureka
  instance:
    #    表示client发送心跳给server端的频率
    lease-renewal-interval-in-seconds: 2
    #    表示server至上次收到client的心跳之后，等待下一次心跳的超时时间，超时则移除
    lease-expiration-duration-in-seconds: 2

    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#手动刷新
management:
  security:
    enabled: false

zuul:
  routes:
    dm-user-consumer: /user/**




